on:
  push:
    tags:
      - 'v*' # Triggers on version tags

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion:
          - '2.x'
        os:
          - ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: iffy/install-nim@v4
      with:
        version: ${{ matrix.nimversion }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get tag version
      id: get_version
      run: |
        git config --global user.email "atlas-tests-bot@nim-lang.org"
        git config --global user.name "Atlas Tests Bot"
        # Strip the 'v' prefix from the tag
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build Tests
      run: |
        nim atlasTestsCreate

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.get_version.outputs.version }}
        tag_name: v${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}